### ISSUE TITLE
Duplicate View on 10.15.7

### ISSUE THREAD

**Issue by IcedOtaku** [DeveloperMaris/ToolReleases#40]
The first item has been renderd 5 times. Failed to figure out why this happens while reading source code as a junior swift learner.
![Screen Shot 2021-03-16 at 8 00 03 AM](https://user-images.githubusercontent.com/46364143/111243846-b2bfb500-863c-11eb-9291-b9f042ccc648.png)

**Comment by DeveloperMaris** [comment]
Thank you @IcedOtaku for trying to figure this issue out by reading the code and also reporting it here. 
I really appreciate that you took the time to try to figure it on your own! 🙇‍♂️

This is caused by the _human error_ from Apple side. 
The app reads Apple's provided [RSS page](https://developer.apple.com/news/releases/rss/releases.rss) and parse it to generate a [model](https://github.com/DeveloperMaris/ToolReleases/blob/master/ToolReleasesCore/Models/Tool.swift) for each of _item_ in the feed.
As you can see [here](https://github.com/DeveloperMaris/ToolReleases/blob/master/ToolReleasesCore/Models/Tool.swift#L43), to identify the Tool, we use Apple's provided _id_ parameter from the `guid` parameter available from the RSS.
Time-to-time Apple makes a mistake and provides the same `guid` for multiple items in the RSS feed, which results in a duplicate models in the app unfortunately.

<img width="936" alt="Screen Shot 2021-03-16 at 09 11 58" src="https://user-images.githubusercontent.com/16559687/111270720-e13b9100-8638-11eb-8988-3d00edcf1839.png">

This _id_ parameter is necessary for SwiftUI to be able to display the Tool models in the List properly.

I'm starting to think that it would be better to base the model _id_ parameter not on the `guid` but maybe on the tool version available in the `title`.
For example, _macOS Big Sur 11.3 beta 4 (20E5210c)_ the ** 20E5210c** would be the identifier.

Hope that my comment made it clear, why this is happening @IcedOtaku.
I will look at this issue in the next release cycle.

**Comment by IcedOtaku** [comment]
I never have a thought that this is from the Apple side.
Thank you @DeveloperMaris  for your detailed explanation. It's quite clear for me.

**Comment by DeveloperMaris** [comment]
Yes, this is not the only time Apple provides incorrect information... :) 

https://github.com/DeveloperMaris/ToolReleases/issues/5#issue-652520789

**Comment by DeveloperMaris** [comment]
As you can see, 1 day after they fixed the links, and now the app works correctly. But still I will think about, how to prevent this incorrect display name from the app side.

<img width="703" alt="Screen Shot 2021-03-17 at 09 04 47" src="https://user-images.githubusercontent.com/16559687/111428202-dac41c80-86ff-11eb-9aa4-b089ca32fb7b.png">

**Comment by DeveloperMaris** [comment]
Fixed this in v1.4.1 by providing different tool identifier.
